<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Target .NET 10 -->
    <TargetFramework>net10.0</TargetFramework>

    <!-- Use C# 14 -->
    <LangVersion>14.0</LangVersion>

    <!-- Keep implicit usings and nullable behavior as you like -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Keep package refs, update versions if necessary to net10-compatible releases -->
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
	  <PackageReference Include="System.Linq.Async" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
	  <Folder Include="Features\Mines\Domain\" />
      <Folder Include="Features\Mines\Commands\" />
      <Folder Include="Features\Mines\Repositories\" />
      <Folder Include="Features\Mines\Queries\" />
  </ItemGroup>

</Project>
